---
- name: Converge
  hosts: all
  become: true

  vars:
    ufw_state: disabled
    ufw_rules: []

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - weareinteractive.ufw

  post_tasks:
    - name: Verify UFW is running
      command: ufw status
      changed_when: false
